### ISSUE TITLE
Support for LC6

### ISSUE THREAD

**Issue by rohanki** [erikboto/monark-ant#4]
Some firmware versions of the LC6 seem to identify themselves as their firmware version rather than LC when sending the ID command. eg: MEC3V11R18
The detection method MonarkConnection.cpp is then unable to detect the bike.
All other serial commands are the same.

**Comment by erikboto** [comment]
I'll fix this, thanks for letting me know!

Out of curiosity, are you building it yourself or are you using the Raspberry Pi-image? If you build it yourself, which OS are you using?

**Comment by rohanki** [comment]
I’d love to use the RPI image. I had attempted to make the change and build from source myself, but I’m unfamiliar with QT and was having difficulty working out exactly which version to build with.
I was going to build for Windows or try and build for Raspberry-pi.
I tested the Raspberry-pi image, and apart from no connection to the Monark, it works well.

As an FYI, the Monark Test Touch software identifies our LC6 as an ‘MEC3’, so I’m assuming ‘MEC3’ is the string they match.

**Comment by erikboto** [comment]
Should be fixed with fd8be6191e3c087a151e230743f12e5c75a2536e. I'll leave the bug open until I've built the Raspberry Pi image and gotten confirmation that it works well.

**Comment by erikboto** [comment]
If you have the time and possibility, could you test this image? Should work now. 
http://linode.unixshell.se/monark/image-monark-raspberrypi3_v3-test.zip

**Comment by erikboto** [comment]
Err, that image does not work well. http://linode.unixshell.se/monark/image-monark-raspberrypi3_v3-test2.zip should be better. Sorry about that.

**Comment by rohanki** [comment]
Sorry, I won't be near the bike for another 2 months. But I'll definitely check it then. Thanks again for building the image :)

**Comment by erikboto** [comment]
No worries, I'm pretty certain it should "just work" now anyway. Thanks for reporting!

**Comment by rohanki** [comment]
Good news! Finally back on site with the Monark. Plugged in and all just worked fine! Thanks so much!
Do you have plans to program control over bluetooth for things like Zwift?

**Comment by erikboto** [comment]
It's something I want to do now that they finally got around to creating a standard for it. But currently I don't really have the time.

My next thing will probably be adding buttons on the handlebars that are connected to the Pi which can be used for increasing/decreasing wattage, or "virtual gears" if you use Zwift in simulation mode. But that will be ANT+ only at first.
