### ISSUE TITLE
Indoor Bike Simulation Parameters

### ISSUE THREAD

**Issue by cagnulein** [erikboto/monark-ant#8]
Hi, i'm sorry to bother you, i wrote a similar project ( https://github.com/cagnulein/qdomyos-zwift ) and i have a strange behaviour from zwift. I always saw this pattern:

<pre>
<< recv control request
>> send request control succeed
<< recv start simulation
>> send start simulation succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv control request
>> send request control succeed
<< recv start simulation
>> send start simulation succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
<< recv control request
>> send request control succeed
<< recv start simulation
>> send start simulation succeed
<< recv indoor bike simulation parameters
>> send simulation parameter succeed
....
</pre>

and so on forever. The parameters are changing following the zwift session but i don't understand why zwift still always send the control request and the start simulation. Do you have an idea? Do you have the same behaviour with your monark-ant project?

Thanks!

**Comment by erikboto** [comment]
I just had a look, and I see the exact same behavior here. But as you say everything works as expected. I'm not sure if it's just something Zwift does, or if we're simple not doing something Zwift would expect when it has control and is "started".

**Comment by cagnulein** [comment]
@erikboto thanks for your answer.
I didn't quite mean "work as expected" because i never received a FTMS_SET_TARGET_RESISTANCE_LEVEL or a FTMS_SET_TARGET_POWER. Do you?

**Comment by erikboto** [comment]
I don't think you should get a power or resistence target when you're in simulation mode, I think the power/resistence is derived from the simulation parameters in that case.

If I instead start a workout in Zwift using ERG-mode, I get the FTMS_SET_TARGET_POWER commands.

And when using the TrainerRoad app you can choose to do into resistance mode, the you get a slider so that you can control the resistence level which makes it send the FTMS_SET_TARGET_RESISTANCE_LEVEL command.

**Comment by erikboto** [comment]
I tried FulGaz and Rouvy on my iphone now, just to see how they behave, but I can't make them see my device as controllable. Maybe they're not using simulation and are instead relying on the inclination control mode, which I haven't (yet) added support for.

**Comment by cagnulein** [comment]
fair enough, thanks for your explanation!
